import os 

from dotenv import load_dotenv
load_dotenv()

load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), ".env"))

from google.adk.agents import Agent , ParallelAgent, SequentialAgent

from google.adk.models.lite_llm import LiteLlm
from google.adk.tools import google_search


# linkedInModel=LiteLlm(model=os.getenv("GOOGLE_GENAI_MODEL")
# )
# instagramModel=LiteLlm(model=os.getenv("OPENROUTER_MODEL_SUMMARY"))


# researchModel=model=os.getenv("GOOGLE_GENAI_MODEL")

linkedInModel = LiteLlm(model=os.getenv("GOOGLE_GENAI_MODEL"))
instagramModel = LiteLlm(model=os.getenv("OPENROUTER_MODEL_SUMMARY"))
researchModel = LiteLlm(model=os.getenv("GOOGLE_GENAI_MODEL"))
print("GOOGLE_GENAI_MODEL:", os.getenv("GOOGLE_GENAI_MODEL"))
print("OPENROUTER_MODEL_SUMMARY:", os.getenv("OPENROUTER_MODEL_SUMMARY"))

researchAgent=Agent(
    name="ResearchAgent",
    model=researchModel,
    description="An agent that researches on the given topic and proivdes relevant information to other agent for generating social media post",
    instruction="""
    You are a research assistnat . you will be given a topic and you will research on it . Then you will provide a summary of the research
    """,
    output_key="research_summary"

)


linkedInAgent=Agent(
    model=linkedInModel,
    name="LinkedInPostsAgent",
    description="An agent that generates LinkedIn posts",
    instruction="""
    You are linkedIn post generator. You will be a give a topic with researched summary.from "research_summary" output, and you will generate a LinkedIn Post about it . 
        The post should be professional , enganging , and relevant to the topic . 
        The post shoud have a primary hook , not more that 60 characters.
        The post should have  a post-hook that is either supporting the hook or completely inverse of the hook to grab attention.

        The post should be in conversational tone and should be easy to read. 
        There should be bullet points in the post to make it easy to read. 
        There should be actionable itmes in the post to make it easy to follow.

        At the end of the post, there should be a question to engage the audience. 
        Finally , ask the audience to share their thoughts in the commnets. And to repost 

        Use emojis to make the post more engaging.
        Use hastags to make the post more discoverable.

    """,
    output_key="linkedIn_post"
)

instagramAgent=Agent(
    model=instagramModel,
    name="InstagramReelScriptAgent",
    description="An agent that generates Instagram reel scripts",
    instruction="""
    You are an instagram reel scripts generator. You will be given a topic with researched summary from "research_summary". output , and you will generate a script for an instagram reel about it.
        The script should be engaging, fast paced , and relevant to the topic.
        The script shoudl have a primary hook , which grabs the attention of the audience . 
    
    """,
    output_key="instagram_script"
)


# parallel agent that process two things linkedInAgent , instagramAgent

postsAgent=ParallelAgent(
    sub_agents=[linkedInAgent,instagramAgent],
    description="An agent that generates social media post by using the linkedIn and Instagram agents",
    name="postAgent"
)

# Post merger agent 

postsMergerAgent=Agent(
    model=researchModel,   # or linkedInModel
    name="PostsMergerAgent",
    description="An agent that mergers the posts from the linkedIn and Instagram agents",
    instruction="""
    You are an AI Assisant responsible for combing linkedIn and instagram reels script into a structued output. 
    
     Your primary task is to merge the posts generated by linkedIn and Instagram agents into a single output. Clearly mentioning the platform for each post.
        Input Summaries:
        -LinkedIn Post : {linkedIn_post"}
        -Instagram Reels Script: {instagram_script}

        Output Format :
        -LinkedIn Post: {linkedIn_post}
        -Instagam Reels Script: {instagram_script}
            
    """
)


root_agent=SequentialAgent(
    name="SocialMediaAgent",
    description="An agent that geneartes social media posts by using the research agent and the posts agent",
    sub_agents=[researchAgent,postsAgent,postsMergerAgent]
)